apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/BorchaniSalma/GitOps-Driven-Python-Application-Deployment'
    targetRevision: main
    path: '.'  # Path in the repo where the manifest is stored
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitops-namespace
  syncPolicy:
    automated:
      prune: true  # Deletes resources no longer defined in Git
      selfHeal: true  # Fixes drift from the Git state
