apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: gitops-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: salmaborchani/flask-app:{{github.sha}}  # Dynamic Git SHA as tag
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
