name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build and push Docker image
      - name: Build Docker Image
        run: |
          docker build -t salmaborchani/flask-app:${{ github.sha }} .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push salmaborchani/flask-app:${{ github.sha }}

      # Step 3: Set up Terraform
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.5

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Step 5: Apply Terraform configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
