name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t salmaborchani/flask-app:${{ github.sha }} .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push salmaborchani/flask-app:${{ github.sha }}

      # Step 3: Update Deployment in GitHub
      - name: Update Deployment Manifest
        run: |
          sed -i "s|image: salmaborchani/flask-app:.*|image: salmaborchani/flask-app:${{ github.sha }}|g" deployment.yaml
          git config --global user.email "sborcheni@gmail.com"
          git config --global user.name "BorchaniSalma"
          git add deployment.yaml
          git commit -m "Update deployment to use image ${{ github.sha }}"
          git push origin main
